// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  home_hero_section: defineAsyncComponent(
    () => import("./HomeHeroSection/index.vue"),
  ),
  programs: defineAsyncComponent(() => import("./Programs/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
