// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_us: defineAsyncComponent(() => import("./AboutUs/index.vue")),
  contact_us: defineAsyncComponent(() => import("./ContactUs/index.vue")),
  home_hero_section: defineAsyncComponent(
    () => import("./HomeHeroSection/index.vue"),
  ),
  identity_section: defineAsyncComponent(
    () => import("./IdentitySection/index.vue"),
  ),
  locations: defineAsyncComponent(() => import("./Locations/index.vue")),
  program_details: defineAsyncComponent(
    () => import("./ProgramDetails/index.vue"),
  ),
  program_page: defineAsyncComponent(() => import("./ProgramPage/index.vue")),
  questions_and_answers: defineAsyncComponent(
    () => import("./QuestionsAndAnswers/index.vue"),
  ),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
